---
- name: Stop nginx service.
  command: >
    service nginx stop
- name: Change nginx.conf.
  template: >
    src=nginx.conf.tpl
    dest={{ openresty_nginx_conf_dir }}/nginx.conf
    owner=root
    group=root
    mode=0644
- name: Create replace_resolver.sh.
  template: >
    src=replace_resolver.sh.tpl
    dest={{ openresty_nginx_conf_dir }}/replace_resolver.sh
    owner=root
    group=root
    mode=0755
- name: Exec replace_resolver.sh.
  command: >
    {{ openresty_nginx_conf_dir }}/replace_resolver.sh
- name: Install passlib.
  pip: name=passlib
- name: Create htpassword.
  htpasswd: >
    path="{{ proxy_s3_htpassword }}"
    name="{{ proxy_s3_username }}"
    password="{{ proxy_s3_password }}"
    owner=root
    group=nginx
    mode=0640
- name: Start nginx service.
  command: >
    service nginx start
