#!/usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import json
import os
import shutil
import StringIO
import subprocess
import sys
import tempfile
import time
import urllib2
import yaml

try:
    import configparser
except:
    import ConfigParser as configparser

config_path = './osx/general.cfg'
homebrew_url = 'https://raw.githubusercontent.com/Homebrew/install/master/install'
pip_url = 'https://bootstrap.pypa.io/get-pip.py'
ansible_config = './.ansible.cfg'


def _loading(current=None):
    loading_frames = ['|', '/', '-', '\\']
    current = 0 if current is None or current == len(loading_frames) - 1 else current + 1
    sys.stdout.write("\rwaiting : %s" % loading_frames[current])
    sys.stdout.flush()
    return current


def _install_CLT():
    print 'install command line tools...'

    subprocess.Popen(['xcode-select', '--install'],
                     stdin=subprocess.PIPE,
                     stdout=subprocess.PIPE,
                     stderr=subprocess.PIPE,
                     shell=False)
    progress = None

    while True:
        p = subprocess.Popen(['gcc', '-v'],
                             stdin=subprocess.PIPE,
                             stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE,
                             shell=False)
        if p.wait() == 0:
            print 'command line tools had been installed!!'
            break
        else:
            progress = _loading(progress)
            time.sleep(0.5)


def _install_homebrew():
    print 'install homebrew...'

    res = urllib2.urlopen(homebrew_url)
    codes = res.read()
    subprocess.call(['ruby', '-e', codes], shell=False)


def _change_zsh():
    print 'change login shell...'

    if os.environ['SHELL'] != '/bin/zsh':
        subprocess.call(['chsh', '-s', '/bin/zsh'], shell=False)
    else:
        print 'login shell had been changed!!'


def _install_pip():
    try:
        import pip
    except:
        print 'install pip...'

        res = urllib2.urlopen(pip_url)
        codes = res.read()
        fh = tempfile.NamedTemporaryFile()
        fh.write(codes)
        fh.flush()
        subprocess.call(['sudo', 'python', fh.name], shell=False)


def _install_ansible():
    try:
        import ansible
    except:
        print 'install ansible from pip...'
        subprocess.call(['sudo', 'pip', 'install', 'ansible'], shell=False)


def _clean_ansible_roles(roles_dir):
    if os.path.exists(roles_dir):
        print 'remove roles dir...'
        shutil.rmtree(roles_dir)


def _clone_ansible_roles(roles_repository, roles_dir):
    _clean_ansible_roles(roles_dir)

    subprocess.call(['git', 'clone', roles_repository, roles_dir], shell=False)


def _generate_ansible_config(config):
    fp = tempfile.NamedTemporaryFile()
    fp.write(config['ansible']['config'])
    fp.flush()

    conf = configparser.SafeConfigParser()
    conf.read(fp.name)

    if conf.has_option('defaults', 'roles_path'):
        roles = conf.get('defaults', 'roles_path').split(':')
    else:
        roles = []
    roles.extend([role['directory'] for role in config['ansible']['roles_path']])
    conf.set('defaults', 'roles_path', ':'.join(roles))

    with open(ansible_config, "w") as fh:
        conf.write(fh)

    return ansible_config


def _generate_ansible_vars(config):
    extra_vars = {}
    for pk, pv in config.items():
        if pk != 'ansible':
            for ck, cv in pv.items():
                extra_vars['%s_%s' % (pk, ck)] = cv
    return extra_vars


def _generate_ansible_playbook(config):
    playbook = config['ansible']['playbook']
    playbook[0]['vars'] = _generate_ansible_vars(config)
    playbook[0]['roles'] = config['ansible']['roles']

    return yaml.dump(playbook)


def _excute_ansible_playbook(config):
    os.environ["ANSIBLE_CONFIG"] = _generate_ansible_config(config)

    inventory = tempfile.NamedTemporaryFile()
    inventory.write(config['ansible']['inventory'])
    inventory.flush()

    playbook = tempfile.NamedTemporaryFile()
    playbook.write(_generate_ansible_playbook(config))
    playbook.flush()

    args = ['ansible-playbook', '-i', inventory.name]
    if 'options' in config['ansible']:
        args.extend(config['ansible']['options'])
    args.append(playbook.name)

    from ansible.cli.playbook import PlaybookCLI
    try:
        cli = PlaybookCLI(args)
        cli.parse()
        sys.exit(cli.run())
    except Exception as exception:
        print exception.message


def _main(config):
    _install_CLT()
    _install_homebrew()
    _install_pip()
    _install_ansible()
    for role in config['ansible']['roles_path']:
        _clone_ansible_roles(role['repository'], role['directory'])
    _excute_ansible_playbook(config)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=u'Build environment on OSX')
    parser.add_argument('-c', '--config',
                        action='store',
                        default=config_path,
                        type=str,
                        help='Configuration file path (default: %s)' % config_path)
    args = parser.parse_args()

    with open(args.config, 'r') as file:
        config = yaml.load(file)

    _main(config)
