---
- name: Install dependent packages.
  yum: >
    name="{{ item }}"
    state="present"
  with_items: "{{ xbuild_python_dependent_packages }}"
- name: Install python in xbuild.
  command: >
    {{ xbuild_install_dir_prefix }}/xbuild/python-install {{ xbuild_python_version }}
    {{ xbuild_python_install_dir_prefix }}
    creates={{ xbuild_python_install_dir_prefix }}
- name: Change python directory owner.
  file: >
    path="{{ xbuild_python_install_dir_prefix }}"
    state=directory
    recurse=yes
    owner="{{ xbuild_python_user }}"
    group="{{ xbuild_python_group }}"
    mode=0755
