---
- name: Install dependen packages in pip.
  command: >
    {{ xbuild_python_install_dir_prefix }}/bin/pip install {{ item }}
  with_items: "{{ flashpolicyd_dependent_packages }}"
- name: Create flashpolicyd script file.
  copy: >
    src=flashpolicyd.py
    dest="{{ flashpolicyd_script_file }}"
    mode=0755
- name: Create flashpolicyd service file.
  template: >
    src=flashpolicyd.service.tpl
    dest="{{ flashpolicyd_service_file }}"
    owner=root
    group=root
    mode=0755
- name: Create flashpolicyd conf directory.
  file: >
    path="{{ flashpolicyd_conf_dir }}"
    state=directory
    owner=root
    group=root
    mode=0755
- name: Create policy file.
  template: >
    src=flashpolicy.xml.tpl
    dest="{{ flashpolicyd_policy_file }}"
    owner=root
    group=root
    mode=0644
- name: Create flashpolicyd run directory.
  file: >
    path="{{ flashpolicyd_pid_dir }}"
    state=directory
    owner=root
    group=root
    mode=0755
- name: Create flashpolicyd log directory.
  file: >
    path="{{ flashpolicyd_log_dir }}"
    state=directory
    owner=root
    group=root
    mode=0755
- name: Register and Start flashpolicyd service.
  service: >
    name=flashpolicyd
    state=started
    enabled=yes
