---
  celery_conf_dir: /usr/local/etc/celery
  celery_conf_file: celeryd
  celery_log_dir: /var/log/celery
  celery_log_file: "%N.celery.log"
  celery_pid_dir: /var/run/celery
  celery_pid_file: "%N.celery.pid"
  celery_user: celery
  celery_group: celery
  celery_user_home: "{{ celery_conf_dir }}"
  celery_nodes: worker1 worker2 worker3
  celery_app: proj
  celery_change_dir: /tmp/celery
  celery_opts: --time-limit=300 --concurrency=8
