---
- name: Install dependent packages.
  yum: >
    name="{{ item }}"
    state="present"
  with_items: "{{ wrk_dependent_packages }}"
- name: Clone wrk repository.
  git: >
    repo="{{ wrk_repo }}"
    dest="{{ wrk_src_dir }}"
    update="yes"
    accept_hostkey="yes"
- name: Make wrk.
  command: >
    /usr/bin/make
    chdir={{ wrk_src_dir }}
- name: Create link file.
  file: >
    src="{{ wrk_src_dir }}/wrk"
    dest="{{ wrk_bin_file }}"
    state=link
    owner=root
    group=root
    mode=0755
- name: Create lua script file.
  template: >
    src=script.lua.tpl
    dest="{{ wrk_lua_script_file }}"
    mode=0644
# - name: Benchmark test.
#   shell: "{{ wrk_bin_file }} {{ wrk_option }} {{ bench_url }}"
#   register: result
# - name: Print result.
#   debug: >
#     msg="{{ result.stdout }}"
